### ISSUE TITLE
React console warnings

### ISSUE THREAD

**Issue by tsjoberg** [clayallsopp/react.backbone#35]
First off, Great library! 

I know this doesn't relate to your library specifically but in regards to following the README documentation and some browser console warnings I have seen:

1. `Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory`

2. `Warning: React.renderComponent will be deprecated in a future version. Use React.render instead.`

Some fixes I have done to alleviate those warnings:

1- According to http://fb.me/react-legacyfactory you should create Factory if not using JSX:

`var UserViewComponent = React.createFactory(UserView);`
`var userView = UserViewComponent({model: user});`

2- Not sure if valid but I think `React.renderComponent()` is deprecated for `React.render()` now. 

`React.render(userView, document.getElementById('element'));`

I am still very new to React so this may be isolated to my environment (using requirejs/require-jsx-plugin) and also related to the fact that I am not using JSX to render the component but figure I would pose the question

**Comment by clayallsopp** [comment]
Both fixes make sense - would love a PR to fix the `README` with those changes!

**Comment by markijbema** [comment]
Iirc this has changed in React 0.12. I'd be in favour of such a change, but I think we should do a bigger version bump, since this will make it incompatible with a previous version of react (0.10? 0.11?)

**Comment by clayallsopp** [comment]
@markijbema I believe the warnings @tsjoberg  refers to only happen if you copy+paste the examples from the README, this wouldn't impact the library code itself or require a new version

**Comment by tsjoberg** [comment]
@clayallsopp I think @markijbema is right in that these new implementation methods were only introduced with React 0.12. So in order to follow `.render()` instead of `.renderComponent` one would need React 0.12.x to do so. I believe same goes with `createFactory()`

React 0.12 Changelog: http://facebook.github.io/react/blog/2014/10/28/react-v0.12.html#changelog

To Mark's point I think we would update the package.json (peerDependecies) to include React 0.12:

`"peerDependencies": {
    "react": ">=0.12.x <1.x.x",
    "backbone": "1.x.x"
  },`

And depending ... also incrementing the library version because of this peer dependency change

**Comment by clayallsopp** [comment]
You're both right in that these things are deprecated in React, and we should update the `README` accordingly, but nowhere in the actual react.backbone code do we use `render` or instantiate a component using the legacy method, so no reason to bump the dependencies.

put another way, react.backbone is perfectly compatible with old and future versions of React at this point, without warnings

**Comment by tsjoberg** [comment]
makes sense @clayallsopp will open PR soon for `readme` updates
