### ISSUE TITLE
backbone-react-component

### ISSUE THREAD

**Issue by ram-you** [clayallsopp/react.backbone#46]
Hi,
What are differences with **backbone-react-component** _https://github.com/magalhas/backbone-react-component_  **?**
Thank you for your clarification.

**Comment by yukw777** [comment]
+1

**Comment by ORESoftware** [comment]
+1

**Comment by ChiefORZ** [comment]
In a nutshell, it is a different way to implement the same functionality.

What I like about clayallsopp/react.backbone is:
* that it has an smaller footprint
* the fewer lines of code are straight forward and made it possible to easily modify the mixin for my project
* and what i like the most: it binds all possible  change methods of the model/collection to the component... with magalhas/backbone-react-component you have to do it manually.
