### ISSUE TITLE
createClass() will be removed from React

### ISSUE THREAD

**Issue by showmeyourhits** [clayallsopp/react.backbone#54]
Howdy,

createClass() will be removed from React in 16 version. Are you going to update your lib?

**Comment by kyllle** [comment]
@clayallsopp do you plan to upgrade this plugin to support React v16 or should we be making efforts to create-react-class as advised by in the console warnings?

Cheers
Kyle

**Comment by markijbema** [comment]
If anyone makes a PR,  I will review it and publish the package. @clayallsopp nor me is currently actively developing the package

**Comment by showmeyourhits** [comment]
Ok i'll try, but since React no longer supporting mixins, update will have breaking changes: package function will be used as HOC.
```
class YourComponent extends React.Component {...}

connectToBackbone(YourComponent, options);
```
