### ISSUE TITLE
component.isMounted() is deprecated

### ISSUE THREAD

**Issue by kneem** [clayallsopp/react.backbone#55]
Hello!

`component.isMounted()` [has been deprecated in React](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html), and it is being invoked [here](https://github.com/clayallsopp/react.backbone/blob/642d350400d95ae9d2a8674c931be6c4547a88aa/react.backbone.js#L36), which generates the following warning from React:

<img width="719" alt="screen shot 2017-11-16 at 6 11 24 pm" src="https://user-images.githubusercontent.com/6894781/32926039-d4837a3e-caf9-11e7-91ed-8c973b7240fd.png">

I'm using React/ReactDOM v15.6.1.

From the article I mentioned, they do recommend the following:
> An easy migration strategy for anyone upgrading their code to avoid isMounted() is to track the mounted status yourself. Just set a _isMounted property to true in componentDidMount and set it to false in componentWillUnmount, and use this variable to check your component’s status.

Are there any plans to fix this?

Side question: Is this library still maintained? It's been well over a year since the last commit.

**Comment by markijbema** [comment]
Hey @kneem ; I personally don't use the library anymore, so I'm not actively contributing. As for @clayallsopp I don't know. However, I keep an eye on it so I can approve PRs, so if you would be so kind to fix this warning I will look at your PR and merge it if it looks good.

**Comment by workshur** [comment]
Guys, I've created PR with fix for this issue. https://github.com/clayallsopp/react.backbone/pull/56

**Comment by kneem** [comment]
Thanks @workshur @markijbema!

**Comment by markijbema** [comment]
Version 0.9.2 contains the fix. Thanks @workshur !
